package com.jsmacrosce.jsmacros.graal.language.impl;

import java.util.function.UnaryOperator;

/**
 * Provides host-class lookup across the mod/script loader and the separately
 * loaded Graal extension.
 *
 * <p>Lookup preserves the reflection loader's precedence, then tries legacy
 * package-name redirection through that same loader. Only when neither lookup
 * succeeds does it delegate the redirected name to the extension loader.</p>
 *
 * <p>Adapters generated by {@code Java.extend(...)} reference Graal's
 * {@code org.graalvm.polyglot.Value}, which may be invisible to the mod loader.
 * Delegating to the existing extension loader makes those references available
 * while preserving the runtime's class identities; this loader does not define
 * copies of mod or Graal classes.</p>
 */
final class GraalHostClassLoader extends ClassLoader {
    private final ClassLoader extensionLoader;
    private final UnaryOperator<String> redirect;

    /**
     * Creates a host loader with reflection lookup as its parent and extension
     * lookup as its fallback.
     *
     * @param reflectionLoader loader for mod classes and jars loaded by scripts
     * @param extensionLoader loader that owns the Graal extension and its dependencies
     * @param redirect package-name transformation; returns the original name when
     *                 no redirection applies
     */
    GraalHostClassLoader(ClassLoader reflectionLoader, ClassLoader extensionLoader, UnaryOperator<String> redirect) {
        super(reflectionLoader);
        this.extensionLoader = extensionLoader;
        this.redirect = redirect;
    }

    /**
     * Loads the requested name through the parent, then its redirected name
     * through the parent, and finally the redirected name through the extension
     * loader. A failure other than {@link ClassNotFoundException} is not treated
     * as a reason to try another loader.
     *
     * @param name binary name of the requested class
     * @param resolve whether parent lookup should resolve the returned class;
     *                extension fallback uses {@link ClassLoader#loadClass(String)}
     * @return the class supplied by the parent or extension loader
     * @throws ClassNotFoundException if all applicable lookups fail
     */
    @Override
    protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
        try {
            return super.loadClass(name, resolve);
        } catch (ClassNotFoundException missing) {
            String redirected = redirect.apply(name);
            if (!redirected.equals(name)) {
                try {
                    return super.loadClass(redirected, resolve);
                } catch (ClassNotFoundException ignored) {
                    // Legacy extension names may be available only through the extension loader.
                }
            }
            // Generated Graal adapters reference Value; it must have the runtime's original class identity.
            return extensionLoader.loadClass(redirected);
        }
    }
}
