minecraft_version=26.1
minecraft_version_range=[26.1]
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.145.1+26.1
fabric_loader_version=0.19.5

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.109
neoforge_loader_version_range=[4,)

# https://modrinth.com/mod/modmenu/versions?g=26.1
mod_menu_version=18.0.1

# Java 25 since 26.1
java_version=25
