minecraft_version=1.21.5
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.5-20250325.162830
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.5
parchment_version=2025.06.15

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.128.2+1.21.5
fabric_loader_version=0.18.4

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=21.5.96
neoforge_loader_version_range=[4,)

# https://modrinth.com/mod/modmenu/versions?g=1.21.5
mod_menu_version=14.0.0
